#ifndef __TANGRAMFrame__
#define __TANGRAMFrame__

/**
@file
Subclass of Frame, _which is generated by wxFormBuilder.
*/

#include "TANGRAM.h"

//// end generated include
#include <wx/filedlg.h>
#include <wx/dcmemory.h>
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
#include <wx/colourdata.h>
#include <wx/colordlg.h>
#include <memory>
#include"Element.h"
#include<cstdlib>
#include<time.h>
/** Implementing Frame */
class TANGRAMFrame : public Frame
{

protected:
	// Handlers for Frame events.
	void MouseClick(wxMouseEvent& event); //22.05
	void MouseUp(wxMouseEvent& event); //22.05
	void MouseMotion(wxMouseEvent& event);
	void symetriaButtonClick(wxCommandEvent& event);
	void obrotPrawoUpdate(wxScrollEvent& event);
	void obrotLewoUpdate(wxScrollEvent& event);
	void cleanButtonClick(wxCommandEvent& event);
	void startButtonClick(wxCommandEvent& event);
	void zmienKolorButtonClick(wxCommandEvent& event);
	void UpdateUI(wxUpdateUIEvent& event);
	void losowanie();
	void stopnie45Button(wxCommandEvent& event);
	void stopnie90Button(wxCommandEvent& event);
	void stopnie135Button(wxCommandEvent& event);
	void stopnie180Button(wxCommandEvent& event);
	void stopnie225Button(wxCommandEvent& event);
	void stopnie270Button(wxCommandEvent& event);
	void stopnie315Button(wxCommandEvent& event);
	void makeStartSquare();

public:
	/** Constructor */
	TANGRAMFrame(wxWindow* parent);
	//// end generated class members

	void Draw();
	wxImage ksztaltImage;
	int wylosowana;
	Element * _which;//ktory element jest nacisniety
	void Rozszczepienie(wxBufferedDC dc);
	//void closeWindow(wxKeyEvent &event);
	//void keyMove(wxKeyEvent& event, Element &elem);
	void moveShape(int mouseX, int mouseY, Element &shape);

protected:

	//edited 21.05
	Triangle bigTriangle1;
	Triangle bigTriangle2;
	Triangle _middleTriangle;
	Triangle smallTriangle1;
	Triangle smallTriangle2;
	Square square;
	Parallelogram parallelogram;
	wxPoint firstMousePosition;
	int menuWidth;//poprzednia szerokosc okna
	int menuHeight;//poprzednia dlugosc okna
	bool isStartButtonClicked = false;
	bool isBlackColour = false;
	double licznik = 0;
	//end editing

};

#endif // __TANGRAMFrame__